steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --build-arg
      - NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${_CLERK_PK}
      - -t
      - ${_IMG}
      - .
images:
  - ${_IMG}
options:
  logging: CLOUD_LOGGING_ONLY
substitutions:
  _CLERK_PK: ""
  _IMG: ""
